name: CI/CD Workflow for driver-did-btcr

on:
  push:
    branches:
      - master
    paths:
      - 'drivers/btcr/*'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Docker Build and Push
      uses: philpotisk/github-action-docker-build-push@master
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        DOCKER_FILE: docker/Dockerfile
        CONTAINER_TAG: phil21/driver-did-btcr:latest
        BUILD_PATH: ./drivers/btcr
    - name: Update EKS
      uses: ./actions/deploy-eks
      env:
        CONTAINER_PATH: ./drivers/btcr
        CONTAINER_NAME: driver-did-btcr
        KUBE_CONFIG_DATA: ${{secrets.KUBE_CONFIG_DATA}}
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}