name: CI/CD Workflow for Universal Resolver Web

on:
  push, pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Docker Build and Push
      uses: philpotisk/github-action-docker-build-push@master
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        DOCKER_FILE: docker/Dockerfile-uni-resolver-web
        CONTAINER_TAG: phil21/uni-resolver-web:latest
        BUILD_PATH: ./resolver/java