name: CI/CD Workflow for Universal Resolver Web
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Build and Push
      uses: philpotisk/github-action-docker-build-push@master
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        DOCKER_FILE: docker/Dockerfile-uni-resolver-web
        CONTAINER_TAG: phil21/uni-resolver-web:latest
        BUILD_PATH: ./resolver/java
    - name: Update EKS
      uses: philpotisk/github-action-maven-sonarcloud@master
      env:
        BUILD_PATH: ./resolver/java
        SONAR_ORG: ${{secrets.SONAR_ORG}}
        SONAR_LOGIN: ${{secrets.SONAR_LOGIN}}