name: CI/CD Workflow for Universal Resolver Web
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Build and Push
      uses: philpotisk/github-action-docker-build-push@master
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        DOCKER_FILE: docker/Dockerfile-uni-resolver-web
        CONTAINER_TAG: phil21/uni-resolver-web:3.1.0
        BUILD_PATH: ./resolver/java
    - name: Update EKS
      uses: philpotisk/github-action-deploy-eks@master
      env:
        CONTAINER_PATH: ./resolver/java
        CONTAINER_NAME: uni-resolver-web
        KUBE_CONFIG_DATA: ${{secrets.KUBE_CONFIG_DATA}}
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        EXTERNAL_GIT_KEY: ${{secrets.EXTERNAL_GIT_KEY}}