name: CI/CD Workflow for Universal Resolver

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Docker Build and Push
      uses: ./actions/docker-push
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        CONTAINER_TAG: phil21/driver-did-btcr:latest
        BUILD_PATH: ./drivers/btcr
    - name: Update EKS
      uses: ./actions/deploy-eks
      env:
        DRIVER_PATH: ./drivers/btcr
        DRIVER_NAME: driver-did-btcr
        KUBE_CONFIG_DATA: ${{secrets.KUBE_CONFIG_DATA}}
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}