name: CI/CD Workflow for Universal Resolver

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Docker Build and Push
      uses: ./actions/docker-push
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        CONTAINER_TAG: phil21/driver-did-btc:latest
        BUILD_PATH: ./universal-resolver/drivers/btcr